function getRandomImage() {
//declare an array to store the images
var randomImage = new Array();

//insert the URL of images in array
randomImage[0] = "images/dog1.jpeg";
randomImage[1] = "images/dog2.jpeg";
randomImage[2] = "images/dog3.jpg";
randomImage[3] = "images/dog4.jpeg";
randomImage[4] = "images/dog5.jpeg";


//generate a number and provide to the image to generate randomly
var number = Math.floor(Math.random()*randomImage.length);

//return the images generated by a random number
return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';
}
